### ISSUE TITLE
Support for keybinds set in mod menus and not the vanilla section

### ISSUE THREAD

**Issue by BumbleTree** [HVB007og/KeybindsGalore_HVB007_1.20.x#2]
I'm unsure whether this is possible but wondering if would be able to intercept key binds that are set in individual mod GUIs that don't appear in the vanilla Minecraft keybind menu.
For example on this mod https://www.curseforge.com/minecraft/mc-mods/plasmo-voice
<img width="1393" alt="image" src="https://github.com/HVB007og/KeybindsGalore_HVB007_1.20.x/assets/77128029/707acf1e-97d5-4a55-b66f-05e3c18fdac8">
It has its own GUI where key binds are set. And if using a key bind that conflicts, it presses both rather than having any option.
I suspect this isn't possible without deep diving into individual mods code to see how key binds work and implementing solutions on a per mod basis. However a man can dream.
Thanks for the work.

If it helps at all the keybinds are handled by the mod here. https://github.com/plasmoapp/plasmo-voice/tree/120f5a8681a69cb85eb4a4c744aafa627ca1cd38/client/src/main/java/su/plo/voice/client/config/keybind

**Comment by HVB007og** [comment]
Currently I don't see a way to intercept the key binds and it's not being developed on actively by me. There are other features that I would like to implement first, then I'll look into this issue.
