### ISSUE TITLE
No support for 1.20.4

### ISSUE THREAD

**Issue by Sitolam** [HVB007og/KeybindsGalore_HVB007_1.20.x#5]
Pls add support

**Comment by HVB007og** [comment]
I wasnt able to reproduce, it is working fine for me on 1.20.4 Fabric while using the following mods:
Fabric API - 0.97.0+1.20.4
Keybinds Galore - 0.2-1.20
Mod Menu - 9.2.0-beta.2
Reese's Sodium Options - 1.7.2+mc1.20.4-build.102
Sodium - 0.5.8+mc1.20.4
Sodium Extra - 0.5.4+mc1.20.4-build.116




Closing this issue now.
Please give more feedback and/or logs and check other mods that might be conflicting(there aren't known conflicts yet)

**Comment by HVB007og** [comment]
I wasnt able to reproduce, it is working fine for me on 1.20.4 Fabric while using the following mods:

Fabric API - 0.97.0+1.20.4
Keybinds Galore - 0.2-1.20
Mod Menu - 9.2.0-beta.2
Reese's Sodium Options - 1.7.2+mc1.20.4-build.102
Sodium - 0.5.8+mc1.20.4
Sodium Extra - 0.5.4+mc1.20.4-build.116

Closing this issue now.
Please give more feedback and/or logs and check other mods that might be conflicting(there aren't known conflicts yet)
